# Generated by Django 2.2.3 on 2019-07-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_term_goals', models.TextField(max_length=2000)),
                ('short_term_goals', models.TextField(max_length=2000)),
            ],
        ),
    ]
