# Generated by Django 2.2.3 on 2019-07-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_goals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='goals',
            new_name='goal',
        ),
    ]
