# Generated by Django 2.2.3 on 2019-07-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190720_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='adm_FeeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=50)),
                ('semester', models.PositiveSmallIntegerField()),
                ('day_scholar_fee', models.IntegerField()),
                ('boys_hostel_fee', models.IntegerField()),
                ('girls_hostel_fee', models.IntegerField()),
                ('total_fee_for_hosteller_boys', models.IntegerField()),
                ('total_fee_for_hosteller_girls', models.IntegerField()),
            ],
        ),
    ]
