# Generated by Django 2.2.3 on 2019-07-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_finance_committe'),
    ]

    operations = [
        migrations.CreateModel(
            name='gov_type_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gov_type', models.CharField(max_length=50)),
                ('type_id', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='governence_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='governence_files')),
                ('gov_type', models.IntegerField(max_length=2)),
            ],
        ),
    ]
