# Generated by Django 2.2.3 on 2019-07-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_gov_type_table_governence_files'),
        ('website', '0004_adm_feestructure'),
    ]

    operations = [
    ]
