# Generated by Django 2.2.3 on 2019-07-26 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_merge_20190726_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_Name', models.CharField(max_length=50)),
                ('element_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Academics_elements_FileTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_fileTypeName', models.CharField(max_length=50)),
                ('FileTypeId', models.IntegerField()),
                ('element_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Academics')),
            ],
        ),
        migrations.CreateModel(
            name='campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='course_Type_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(max_length=50)),
                ('course_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cultural_Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cultural_Committee_Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('History', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Members_of_Examination_Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Committee_members', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='principal_desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_img', models.ImageField(upload_to='images/', verbose_name='Upload Image')),
                ('principal_name', models.CharField(max_length=25)),
                ('principal_message', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='QualityWork_elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=100)),
                ('element_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Roll_of_Honour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=50)),
                ('file_ROH', models.FileField(upload_to='Roll_of_hrn_files')),
            ],
        ),
        migrations.CreateModel(
            name='Software_Automation_Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Committee_members', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supporting_Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Committee_members', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='governence_files',
            name='gov_type',
        ),
        migrations.AddField(
            model_name='balance_sheet',
            name='Name',
            field=models.CharField(default='Default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='governence_files',
            name='Name_of_file',
            field=models.CharField(default='Default', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='governence_files',
            name='type_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.gov_type_table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finance_committe',
            name='Details',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='finance_committe',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='QW_elements_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfFile', models.CharField(max_length=200)),
                ('elements_file', models.FileField(upload_to='', verbose_name='Upload File')),
                ('element_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.QualityWork_elements')),
            ],
        ),
        migrations.CreateModel(
            name='branchInCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('intake', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.course_Type_table')),
            ],
        ),
        migrations.CreateModel(
            name='Academics_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=50)),
                ('File', models.FileField(upload_to='', verbose_name='Upload File')),
                ('FileTypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Academics_elements_FileTypes')),
            ],
        ),
    ]
