# Generated by Django 2.2.3 on 2019-07-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mission', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vision', models.TextField(max_length=2000)),
            ],
        ),
    ]
