# Generated by Django 2.2.3 on 2019-07-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Long_term_goals', models.TextField(max_length=500)),
                ('Short_term_goals', models.TextField(max_length=500)),
            ],
        ),
    ]
