# Generated by Django 2.2.3 on 2019-07-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_balancs_sheet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Balancs_Sheet',
            new_name='Balance_Sheet',
        ),
    ]
