# Generated by Django 2.2.3 on 2019-07-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_lol'),
    ]

    operations = [
        migrations.CreateModel(
            name='vision1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision1', models.TextField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='lol',
        ),
    ]
