# Generated by Django 2.2.3 on 2019-07-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190719_0713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vision1',
        ),
    ]
