# Generated by Django 2.2.3 on 2019-07-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190720_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='principal_desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_img', models.ImageField(upload_to='images/')),
                ('principal_message', models.TextField(max_length=2000)),
            ],
        ),
    ]
