# Generated by Django 2.2.3 on 2019-07-18 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(choices=[('computer science', 'CSE'), ('mechanical engg', 'ME'), ('civil engg', 'CE'), ('electrical engg', 'EE'), ('electronics engg', 'ECE'), ('production engg', 'PE')], default='computer science', max_length=20)),
                ('Obt_fil', models.CharField(choices=[('obtained', 'Obtained'), ('filed', 'Filed')], max_length=20, verbose_name='Obtained or filed')),
                ('Patent_title', models.CharField(max_length=20)),
                ('Patent_type', models.CharField(max_length=20)),
                ('Patent_application_no', models.CharField(max_length=20)),
                ('Patent_grant_year', models.CharField(max_length=20)),
                ('Commercialized', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='YES', max_length=20)),
                ('Licence_fee', models.IntegerField(max_length=100000)),
                ('Technology_transferred', models.CharField(max_length=20)),
                ('Organisation_name', models.CharField(max_length=20)),
                ('Application_date', models.DateField(default=datetime.date.today)),
                ('Application_no', models.CharField(max_length=20)),
            ],
        ),
    ]
